### PR TITLE
Do not always match bidirectionnaly

### LINKED ISSUE #56: Match query matches bidirectionnaly
See https://groups.google.com/d/msg/rabbitmq-users/IWkEmwLXtJg/6iUypLyeDAAJ

This can authorize unexpected actions, e.g. with

```erlang
{resource_access_query, {match, {string, "${name}"}, {string, "^${username}-"}}}
```

For user `Alice`, this lets create `Alice-test` queue (expected), but also `Ali` (not expected).

Configuration to reproduce:

```erlang
[
	{rabbit, [{auth_backends, [rabbit_auth_backend_ldap]}]},
	{rabbitmq_auth_backend_ldap, [
          {servers, ["localhost"]},
          {user_dn_pattern,    "cn=${username},ou=People,dc=rabbitmq,dc=com"},
          {other_bind,         anon},
          {use_ssl,            false},
          {group_lookup_base,  "ou=groups,dc=rabbitmq,dc=com"},
          {use_ssl,            false},
          {port,               389},
          {log,                true},
	  {idle_timeout,	infinity}, 
          {vhost_access_query, {constant, true}},
          {tag_queries, [{monitor,       {constant, true}},
                                 {administrator, {constant, false}},
                                 {management,    {constant, false}}]},
          {resource_access_query, {match, {string, "${name}"}, {string, "^${username}-"}}}
   ]}
].
``` 
From the plugin directory:
```
example/setup.sh
```

Feed the LDAP directory with `rabbit_ldap_seed:seed/1` and run the broker:

```
make run-broker RABBITMQ_CONFIG_FILE=ldap
```

Java program to reproduce:
```java
ConnectionFactory connectionFactory = new ConnectionFactory();
connectionFactory.setUsername("Alice");
connectionFactory.setPassword("password");
Connection connection = connectionFactory.newConnection();
Channel channel = connection.createChannel();
// passes
channel.queueDeclare("Alice-test", false, true, true, null);
// passes, but shouldn't
channel.queueDeclare("Ali", false, true, true, null);
connection.close();
```

### PR DESCRIPTION
**Pull request by acogoluegnes**
Fixes #56

### CODE REVIEW

File: src/rabbit_auth_backend_ldap.erl [hunk 1]
```diff
@@ -208,13 +208,20 @@ evaluate0({equals, StringQuery1, StringQuery2}, Args, User, LDAP) ->
               evaluate(StringQuery1, Args, User, LDAP),
               evaluate(StringQuery2, Args, User, LDAP));
 
-evaluate0({match, StringQuery, REQuery}, Args, User, LDAP) ->
+evaluate0({match, {string, _} = StringQuery, {string, _} = REQuery}, Args, User, LDAP) ->
```
Comment (kjnilsson) [inline src/rabbit_auth_backend_ldap.erl:211]: The documentation states that strings can also be represented by plain strings which won't be included by this special case. Probably need to add another clause to check when `StringQuery` and `REQuery` are both lists.

**Review by kjnilsson — CHANGES_REQUESTED** [review]
