### PR TITLE
Purge defunct connections in more cases

### LINKED ISSUE #92: Backend does not purge connection when LDAP server restarted
First reported in [this `rabbitmq-users` thread](https://groups.google.com/d/msg/rabbitmq-users/kpxxDzS-LaA/discussion).

Reproduction steps using 3.7.5:

* Start LDAP server, start RMQ configured to use LDAP auth (attached)
* Open Mgmt UI and log in, use 5 second refresh to keep querying LDAP
* Stop LDAP server and restart it. In my Windows AD environment, I just stopped the service and restarted it

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #92

This PR will purge defunct connections in a few more cases than before.

### CODE REVIEW

File: src/rabbit_auth_backend_ldap.erl [hunk 1]
```diff
@@ -510,11 +508,13 @@ with_login(Creds, Servers, Opts, Fun, RetriesLeft) ->
...
                             {refused, UserDN, []};
                         {error, ldap_closed} ->
+                            purge_connection(Creds, Servers, Opts),
                             with_login(Creds, Servers, Opts, Fun, RetriesLeft - 1);
                         {error, {gen_tcp_error, _}} ->
+                            purge_connection(Creds, Servers, Opts),
                             with_login(Creds, Servers, Opts, Fun, RetriesLeft - 1);
                         {error, E} ->
-                            ?L1("bind error: ~s ~p",
+                            ?L1("bind error: ~p ~p",
```
Comment (lukebakken) [inline src/rabbit_auth_backend_ldap.erl:517]: I modified this because the format of `E` doesn't always follow `~s ~p` as seen in the log:

```
2018-05-30 10:36:17.087 [info] <0.291.0> FORMAT ERROR: "    LDAP bind error: ~s ~p~n" [{error,ldap_connect_error},{'EXIT...
```

**Review by michaelklishin — APPROVED** [review]

**Comment by lukebakken** [comment]
Thanks @michaelklishin
